import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import AuthChecker from '@/app/hooks/use-auth-check'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthChecker>
        <body className={inter.className}>{children}</body>
      </AuthChecker>
    </html>
  )
}
